### ISSUE TITLE
can't install Collection

### ISSUE THREAD

**Issue by coke** [finanalyst/collection#3]
===> Building: Collection:ver<0.15.8>:auth<zef:finanalyst>
[Collection] Released plugin directory exists at ｢/Users/coke/.local/share/Collection｣
[Collection] From https://github.com/finanalyst/collection-plugins
[Collection]    677b2a1..30f02f3  main       -> origin/main
[Collection] error: Your local changes to the following files would be overwritten by merge:
[Collection] 	plugins/html/typegraph_v0_auth_collection/typegraphs/Int.svg
[Collection] Please commit your changes or stash them before you merge.
[Collection] Aborting
===> Building [FAIL]: Collection:ver<0.15.8>:auth<zef:finanalyst>
Aborting due to build failure: Collection:ver<0.15.8>:auth<zef:finanalyst> (use --force-build to override)

**Comment by finanalyst** [comment]
This is an issue I have encountered occasionally when `.local/share/Collection` gets out of sync with the github repository. It is probably because `git` is being called incorrectly for the situation. 

Workaround for the time being is to delete `.local/share/Collection` altogether and reinstall Collection.

**Comment by finanalyst** [comment]
@coke On reflection, is there a problem on case-relaxed disks where `int.svg` overwrites `Int.svg`, thus pushing the local repository out of sync with the github one? 

That means that the local repository will be out of sync after every update. If there is a way to fix the problem off int/Int for case-relaxed disks, I will implement it as soon as possible. I need some help here to figure out a way to do this.

**Comment by coke** [comment]
Followup issue, after removing the .local Collection folder

```
[Collection] Released plugin directory created as ｢/Users/coke/.local/share/Collection｣
[Collection] Cloning into '/Users/coke/.local/share/Collection'...
[Collection] warning: the following paths have collided (e.g. case-sensitive paths
[Collection] on a case-insensitive filesystem) and only one from the same
[Collection] colliding group is in the working tree:
[Collection]   'plugins/html/camelia_v0_auth_collection/images/Camelia-404.png'
[Collection]   'plugins/html/camelia_v0_auth_collection/images/camelia-404.png'
```

**Comment by coke** [comment]
I need a way to override  as ｢/Users/coke/.local/share/Collection｣ - my home dir is not on a case sensitive file system, but I do have a volume I can use that is.

**Comment by finanalyst** [comment]
@coke Not sure how much you have already worked out - I had to look back too.

You are facing this problem - I think - because you are using Collection in a way that calls RefreshPlugins. 
For the Raku/doc-webite repo, I explicitly removed the call to RefreshPlugin by creating `bin_files/build-site`, which relies on its own plugins.

To run Collection in the way I do to generate new-raku.finanalyst.org, you will need to clone and install [Collection-Raku-Documentation](https://github.com/finanalyst/collection-raku-documentation.git), which contains the utility `Raku-Doc`.

I have not paid much attention to making Collection as generic as possible.

Here is the workaround for what you want. 

In the installation section of README.md in Collection repo, there is the section
```
PluginPath=~/.Collection zef install Collection
```
This is giving a path to the Build.pm6 program.

In Build.pm6, the directory into which the most uptodate plugins are clone can be overriden from `$*HOME/.local/share/Collection` to the contents of `%*ENV<PluginPath>`.
All Build is doing is to clone `'https://github.com/finanalyst/collection-plugins'` to that directory.

The path to plugins is also set in the file `SomeCollectionName/plugins.rakuon`, which is a Hash, and the key is `_metadata_=>collection-plugin-root`. The design aim here is to allow for moving the collection plugin directory on a per collection. 'SomeCollectionName' is the name of the directory in which a collection is created.

So, in order to change after installation:
1. clone the collections-plugins repo in some place convenient for you,
2. delete ｢/Users/coke/.local/share/Collection｣ 
3. delete the file `SomeCollectionName/plugins.rakuon`
4. run `Raku-Doc` again
  - at the stage when Refresh plugins is called, you will be asked for the directory of the plugins.
  - the file `manifest.rakuon` will be created with the correct directory, and you should have no further problem.

**Comment by finanalyst** [comment]
Download is not removed. Delete ｢/Users/coke/.local/share/Collection｣

**Comment by coke** [comment]
I uninstalled Collection and reinstalled it (without removing that directory), and it installed without complaint.
